
services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map frontend container port 3000 to host port 3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
    environment:
       DB_NAME: user_auth
       DB_USER: root
       DB_PASSWORD: root
       DB_HOST: db  # Connects to MySQL service
       JWT_SECRET: user_security_auth
    ports:
      - "5000:5000"  # Map backend container port 5000 to host port 5000
    depends_on:
      - mysql
    volumes:
      - ./backend/.env:/app/.env  # Mount the .env file into the backend container
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_db_name
    ports:
      - "3307:3306"  # Expose MySQL port to the host
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
